baseurl = "https://eizi2002.github.io/"
title = "Leies"
theme = "hugo-theme-nix"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
disqusShortname = "leies-1"

[menu]
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

  [[menu.header]]
    name = "blog"
    weight = 2
    url = "https://eizi2002.skr.jp/"

  [[menu.header]]
    name = "Misskey-orz"
    url = "/misskey"
    weight = 20

[params]
  GithubID = "eizi2002"
  TwitterID = "Leies_202"
  FacebookID = "eizi2002c"
  TelegramID = "Leies_202"
  Name = "Leies"
  HeaderUsername = "Leies_202"
  HeaderHostname = "orz"
  Email = "lei@eizi2002.skr.jp"
  About = "そこいらの開発者未満です。もう一つのサイト:https://eizi2002.skr.jp/"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
  SlackURL = "https://leies202.slack.com/"

